spring:
  application:
    name: eureka-web
eureka:
  client:
    service-url:
      defaultZone: http://mse-4439ed32-eureka.mse.aliyuncs.com:8761/eureka/
server:
  port: 8080
feign:
    enabled: true