spring:
  application:
    # 指定微服务的名称，后续在调用的时候，只需要使用该名称就可以进行服务访问
    name: eureka-server
server:
  port: 8080
eureka:
  client:
    service-url:
      # 服务注册中心的配置内容，指定服务注册中心的 url
      defaultZone: http://mse-4439ed32-eureka.mse.aliyuncs.com:8761/eureka/
  instance:
    prefer-ip-address: true