---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.24
  name: eureka-web
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
  selector:
    app: eureka-web
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: eureka-web
  name: eureka-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-web
  template:
    metadata:
      annotations:
        ahasPilotAutoEnable: 'on'  #启用ahas  serverless集群暂时不支持该方法
        ahasAppName: eureka-web-ahas  #ahas里的应用名
        armsPilotAutoEnable: 'on'  #启用arms serverless集群暂时不支持该方法
        armsPilotCreateAppName: eureka-web-arms #arms里的应用名
      labels:
        app: eureka-web
    spec:
      containers:
      - image: registry-vpc.cn-beijing.aliyuncs.com/k8s-demo-dingyue/eureka-web:v6
        name: web
        ports:
        - containerPort: 8080
        env:
          - name: msg
            value: from terway
          - name: TZ
            value: Asia/Shanghai
          ######### 配置 环境变量 ###########  仅需要如下配置环境变量即可，注意开头必须是“aliyun_logs_”开头。其中 test-stdout 和 test-file可以自己定制
          - name: aliyun_logs_eureka-web-stdout
            value: stdout
          - name: aliyun_logs_eureka-web-file
            value: /logs/*.log
          - name: aliyun_logs_eureka-web-stdout_machinegroup
            value: eureka-web
          - name: eureka.engine.domain
            value: mse-4439ed32-eureka.mse.aliyuncs.com
          ######### 配置vulume mount #######
        volumeMounts:
          - name: volume-sls
            mountPath: /logs
      volumes:
        - name: volume-sls
          emptyDir: {}